### ISSUE TITLE
HMC models

### ISSUE THREAD

**Issue by dPys** [nipreps/EddyMotionCorrection#15]
@arokem -- are there any other models in dipy besides tensor, sfm, csd, and maybe csa that could be worth including?

As for SFM, what about using the [BayesianRidge](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.BayesianRidge.html) solver? ... i.e. where iterations of the entire LOO procedure gradually build a posterior on alpha/lambda? 

Alternatively, or in addition, we might try building a generic subject-movement model using a group of subjects and use its predictions as an initializer for the subject-specific model?

**Comment by arokem** [comment]
> are there any other models in dipy besides tensor, sfm, csd, and maybe csa that could be worth including?

I would not include CSD/CSA. These are models primarily focused on describing the ODF, and not on providing an accurate signal reconstrution. I would definitely include DKI. 

> As for SFM, what about using the BayesianRidge solver? ... i.e. where iterations of the entire LOO procedure gradually build a posterior on alpha/lambda?

I like that idea!

**Comment by oesteban** [comment]
I concur with Ariel's suggestions.

Let's open up new issues for each model we want to implement, and another one for the BayesianRidge solver because it feels like a very promising suggestion.
