### ISSUE TITLE
Transfer to nipreps org?

### ISSUE THREAD

**Issue by oesteban** [nipreps/EddyMotionCorrection#17]
Hi, I think this project could have more visibility (and would be automatically covered by the rest of principles of the framework) in the nipreps org.

WDYT @dPys ?

**Comment by dPys** [comment]
As long as credit will be given where it's due.

**Comment by oesteban** [comment]
Well, I think that's actually pretty well covered (
https://nipreps.org/community/). In particular -
https://nipreps.org/community/CONTRIBUTING/#recognizing-contributions

Also, that's why I'm proposing a transfer, so that the history is preserved.

**Comment by dPys** [comment]
LGTM!

**Comment by arokem** [comment]
+1

**Comment by oesteban** [comment]
Legacy branch created here - https://github.com/nipreps/EddyMotionCorrection/tree/dPys_prototype
