### ISSUE TITLE
Tutorial: implement a ``plot_gradients`` function into our ``DWI`` object

### ISSUE THREAD

**Issue by oesteban** [nipreps/EddyMotionCorrection#24]
Generate plots like http://www.emmanuelcaruyer.com/q-space-sampling.php

(Emmanuel's code: https://github.com/ecaruyer/qspace/blob/master/qspace/visu/visu_points.py - we should not forget to credit both the repo and his paper).

Assigning Seb, as he is already working on this (and he even has a prototype coded!).

cc/ @josephmje please do not duplicate efforts, could you follow up with Seb about this?

**Comment by josephmje** [comment]
Thanks for the links @oesteban.

@sebastientourbier, we were interested in plotting the diffusion gradients for the tutorial. Currently, it uses some simple matplotlib code as shown below. Would you happen to have some other example code I could work off of for the tutorial?

![image](https://user-images.githubusercontent.com/22102194/114196039-fdbca780-991e-11eb-977a-270399aed15c.png)

**Comment by arokem** [comment]
Theres some code like that in dipy.viz.projections

**Comment by oesteban** [comment]
The plan is to have some quick implementation by the tutorial day (DIPY is clearly a great option too - https://dipy.org/documentation/1.4.0./examples_built/gradients_spheres/).

But in the long term, I'd like to see some projection to a plan and be able to visualize the displacements too (i.e., a dot where the original b-vec was and one arrow from there to the new position after rotation). Perhaps using some of these geographical projections -> https://matplotlib.org/stable/gallery/subplots_axes_and_figures/geo_demo.html
