### ISSUE TITLE
Does it make sense to synthesize b-values other than 1000?

### ISSUE THREAD

**Issue by oesteban** [nipreps/EddyMotionCorrection#31]
I'm coming to the realization that it is really unnecessary to simulate gradients stronger than 1000, which has been the de-facto trade-off between SNR and orientation sensitivity.

Almost all general-purpose cost-functions (and particularly implementations mutual information and cross-correlation) will be insensitive to the b-value, while the drop in SNR can definitely have an impact on the registration.

WDYT @arokem @dPys ?

A good thing about this suggestion is that it is trivial to evaluate once we establish a good test bed.

**Comment by arokem** [comment]
The original argument of the Ben-Amitay paper was specifically about high b-values. At these b-values, the image looks so different from the b=0 image that registering to it makes no sense. Think of really high b-values, where only very few parts of the brain have any signal left.

**Comment by oesteban** [comment]
Okay, I'm also thinking that there's not really any advantage because the model is not generating noise. I'll close this and think it through. Thanks for your response.
